### ISSUE TITLE
Not python 3 compatible.

### ISSUE THREAD

**Issue by joe-eklund** [hotsdata/hots-parser#2]
I've run into a Python 2 dependency while trying `pip3 install -r requirements.txt` inside a Python 3 virtual environment.

```
(hots-parser3) joe@mirkwood:~/projects/github/hots-parser$ pip3 install -r requirements.txt 
Collecting jsonpickle (from -r requirements.txt (line 1))
  Using cached jsonpickle-0.9.5.tar.gz
Collecting psycopg2ct (from -r requirements.txt (line 2))
  Using cached psycopg2ct-2.4.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-_58ga757/psycopg2ct/setup.py", line 206
        print '=' * 80
                ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_58ga757/psycopg2ct/

```

Upon further investigation, I see that according to https://pypi.python.org/pypi/psycopg2ct, this package is only tested on Python 2.6+.

I would recommend either removing this package and switching to something Python 3 compatible, or at least putting it in the readme you must use Python 2.

I was able to `pip install -r requirements.txt` in a Python 2 virtual environment no problem though. For now that is the work around.

Edit: This was tested on Ubuntu 17.04, Python 3.5.3, Python 2.7.13, and GCC 6.3.0 20170118.

**Comment by joe-eklund** [comment]
I've started reading through some of the code and see other Python 3 inconsistencies, such as https://github.com/crorella/hots-parser/blob/master/main.py#L76

So really this ticket should be expanded to just be: Be Python 3 compatible.

**Comment by crorella** [comment]
Yes you are right, most of the prints are not Python 3 compatible.  I would love to do it but for now there are other high-pri tasks I'm working on. If you would like to make it python 3 friendly please go ahead and I will help with the review.

**Comment by crorella** [comment]
Addressed in https://github.com/hotsdata/hots-parser/pull/7
